<?php


namespace App\Components\Interactors\CRUD\Card;


use App\Components\Dto\Card\AddCardDto;
use App\Components\Helpers\Entity\Creator\Card\CardCreator;
use App\Components\Interactors\CRUD\Base\AbstractCreateInteractor;
use App\Components\Validation\ApplicationValidatorInterface;
use App\Entity\Card;
use App\Entity\IdentityInterface;
use App\Repository\CardRepository;

final class AddCardInteractor extends AbstractCreateInteractor
{
    public function __construct(
        CardCreator $creator,
        CardRepository $repository,
        ApplicationValidatorInterface $validator
    ) {
        parent::__construct($creator, $repository, $validator);
    }

    /**
     * @param AddCardDto $dto
     *
     * @return Card|IdentityInterface
     */
    public function call($dto)
    {
        return parent::call($dto); // TODO: Change the autogenerated stub
    }
}
